---
- name: Provision AWS EC2 instances
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars/instances.yml
    - vars/default_vars.yml

  tasks:

    - name: Launch instances with required settings
      ec2_instance:
        key_name: "{{ key_name }}"
        name: "{{ item.0.name }}-{{ item.1.seq_num }}"
        launch_template:
          # name: 'jenkinsAgent-lt'
          id: 'lt-01163e43ec148700b'
        network:
          assign_public_ip: "{{ item.1.assign_public_ip | default(false) }}"
        vpc_subnet_id: "{{ item.1.subnet }}"
        region: "{{ region }}"
        state: started
        tags:
          HostGroups: "{{ item.0.name }}"
        wait: yes
      loop: "{{ instances | subelements('subnets') }}"
      register: ec2

    - name: Create in-memory Ansible inventory
      add_host:
        name: "{{ item.instances.0.public_ip_address }}"
        groups:
          - all
          - "{{ item.instances.0.tags.HostGroups }}"
      loop: "{{ ec2.results }}"
      when: item.instances.0.public_ip_address is defined
      changed_when: false

    - name: Wait for SSH
      delegate_to: "{{ item.instances.0.public_dns_name }}"
      wait_for:
        host: "{{ item.instances.0.public_dns_name }}"
        port: 22
        delay: 10   #Wait for 10 seconds before checking port availability
        timeout: 320  #Keep checking  for 320 seconds
        state: started   #Until port is open
      loop: "{{ ec2.results }}"
      when: item.instances.0.public_ip_address is defined
...
